name: CI/CD with Manual QA Approval

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  stage-1:
    name: "Run Tests and Initial Tasks"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Tests
        run: echo "Running tests..."

      # Add other steps as needed here (linting, etc.)

  manual-approval:
    name: "Manual QA Approval"
    runs-on: ubuntu-latest
    needs: stage-1  # This ensures stage-1 runs before this

    environment: QA-Approval  # This references the environment you created

    steps:
      - name: Wait for QA Approval
        run: |
          echo "Waiting for manual approval from QA."
          echo "After approval, the workflow will continue."

  stage-3:
    name: "Final Tasks After Approval"
    runs-on: ubuntu-latest
    needs: manual-approval  # This job waits for approval before running

    steps:
      - name: Run Post-Approval Tasks
        run: echo "Running post-approval tasks..."
